version: "3"
services:
  mysql:
    build: db/
    container_name: mysql
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "True"
    networks:
      - db
  flask:
    container_name: flask
    build: web/
    environment: 
      FLASK_APP: server.py
      FLASK_ENV: development
      CODERBROTHERS_MYSQL_HOST: mysql
    ports:
        - 8080:8080
    networks:
      - db
networks: 
  db: